version: '3'

services:
  web:
    build:
      context: ./backend
    container_name: ai-chef
    image: ai-chef
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    restart: always